#!/bin/sh

INTERFACE_NAME=$(basename "$0")
STATE=$1
FILES=$2
INSTANCE_TYPE=$3
INSTANCE_ID=$4 # From interface_args, defines component's mock env directory.
# Unrelated to component identity

DATA_DIR=${FILES}/data
HEADER_DIR=${FILES}/header


INSTANCE_BASE_DIR=/data/mender-orchestrator/mock-instances
INSTANCE_DIR="$INSTANCE_BASE_DIR/$INSTANCE_ID"


run(){
    local CMD=$1
    >&2 echo "Executing: $CMD"
    eval "$CMD"
}

log(){
    local MSG=$1
    >&2 echo "##### [$INTERFACE_NAME $INSTANCE_ID] $MSG"
}


is_cmd_available() {
    command -v $1 >/dev/null 2>&1 || { log "ERROR: $1 not detected as an executable"; exit 1; }
}

is_cmd_available jq
is_cmd_available cat


# These are when the CLI is invoked with install
case "$STATE" in

    Download)
        NEW_VERSION=$(jq -r --arg iface "$INTERFACE_NAME" '.artifact_provides.["rootfs-image." + $iface + ".version"]' ${HEADER_DIR}/type-info)
        log "$STATE [Attempting update to: $NEW_VERSION]"
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        ;;

    ArtifactInstall)
        NEW_VERSION=$(jq -r --arg iface "$INTERFACE_NAME" '.artifact_provides.["rootfs-image." + $iface + ".version"]' ${HEADER_DIR}/type-info)
        log "$STATE [Attempting update to: $NEW_VERSION]"
        
        CURRENT_PROVIDES=$(cat "$INSTANCE_DIR/Provides" | grep version)
        # The #*= in the parameter expansion removes everything before and including the = character
        CURRENT_VERSION=${CURRENT_PROVIDES#*=}

        TRANSITION_VERSION="$CURRENT_VERSION->$NEW_VERSION"

        echo "$CURRENT_VERSION" > "$INSTANCE_DIR/OldVersionRef"
        sed -i -n '/device_type/p' "$INSTANCE_DIR/Provides"
        echo "version=$TRANSITION_VERSION" >> "$INSTANCE_DIR/Provides"
        echo "$NEW_VERSION" > "$INSTANCE_DIR/NewVersionRef"
        
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        ;;

    ArtifactReboot)
        NEW_VERSION=$(jq -r --arg iface "$INTERFACE_NAME" '.artifact_provides.["rootfs-image." + $iface + ".version"]' ${HEADER_DIR}/type-info)
        log "$STATE [Attempting update to: $NEW_VERSION]"
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        ;;

    NeedsArtifactReboot)
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi

        NEEDS_ARTIFACT_REBOOT=$(cat "$INSTANCE_DIR/NeedsArtifactReboot")

        log "$STATE [Answer: $NEEDS_ARTIFACT_REBOOT]"
        echo $NEEDS_ARTIFACT_REBOOT
        ;;

    NeedsUnpackedArtifact)
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi


        NEEDS_UNPACKED=$(cat "$INSTANCE_DIR/NeedsUnpackedArtifact" 2>/dev/null || echo "No")

        log "$STATE [Answer: $NEEDS_UNPACKED]"
        echo $NEEDS_UNPACKED
        ;;

    SupportsRollback)
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi

        SUPPORTS_ROLLBACK=$(cat "$INSTANCE_DIR/SupportsRollback")

        log "$STATE [Answer: $SUPPORTS_ROLLBACK]"
        echo $SUPPORTS_ROLLBACK
        ;;

    ArtifactRollback)
        ATTEMPTED_UPDATE_VERSION=$(cat "$INSTANCE_DIR/NewVersionRef")
        OLD_VERSION=$(cat "$INSTANCE_DIR/OldVersionRef")
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        log "$STATE [Update to $ATTEMPTED_UPDATE_VERSION didn't work. Rolling back to: $OLD_VERSION]"
        sed -i -n '/device_type/p' "$INSTANCE_DIR/Provides"
        echo "version=$OLD_VERSION" >> "$INSTANCE_DIR/Provides"
        ;;


    ArtifactCommit)
        ATTEMPTED_UPDATE_VERSION=$(cat "$INSTANCE_DIR/NewVersionRef")
        OLD_VERSION=$(cat "$INSTANCE_DIR/OldVersionRef")
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        log "$STATE [Update to $ATTEMPTED_UPDATE_VERSION worked.]"
        # On ArtifactCommit, override also version
        sed -i -n '/device_type/p' "$INSTANCE_DIR/Provides"
        echo "version=$ATTEMPTED_UPDATE_VERSION" >> "$INSTANCE_DIR/Provides"

        ;;


    ArtifactFailure)
        ATTEMPTED_UPDATE_VERSION=$(cat "$INSTANCE_DIR/NewVersionRef")
        OLD_VERSION=$(cat "$INSTANCE_DIR/OldVersionRef")
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        log "$STATE [Update to $ATTEMPTED_UPDATE_VERSION didn't work.]"

        ;;

    Provides)
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        sed "s|^version=|rootfs-image.${INTERFACE_NAME}.version=|" "$INSTANCE_DIR/Provides"

        ;;


    Inventory)
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi

        ;;


    Identity)
        if [ -f "$INSTANCE_DIR/$STATE.FAIL" ]; then
            log "Failing $STATE"
            exit 1
        fi
        cat $INSTANCE_DIR/Identity
        ;;
esac
